void w(int x){oled.writePixel(x,y,1);}
void e(){if(x==120){y+=1;x=0;}else{x+=8;}}

void AB(){w(x+7);e();}
void AC(){w(x+6);e();}
void AD(){w(x+6);AB();}
void AE(){w(x+5);e();}
void AF(){w(x+5);AB();}
void AG(){w(x+5);AC();}
void AH(){w(x+5);AD();}
void AI(){w(x+4);e();}
void AJ(){w(x+4);AB();}
void AK(){w(x+4);AC();}
void AL(){w(x+4);AD();}
void AM(){w(x+4);AE();}
void AN(){w(x+4);AF();}
void AO(){w(x+4);AG();}
void AP(){w(x+4);AH();}
void AQ(){w(x+3);e();}
void AR(){w(x+3);AB();}
void AS(){w(x+3);AC();}
void AT(){w(x+3);AD();}
void AU(){w(x+3);AE();}
void AV(){w(x+3);AF();}
void AW(){w(x+3);AG();}
void AX(){w(x+3);AH();}
void AY(){w(x+3);AI();}
void AZ(){w(x+3);AJ();}
void BA(){w(x+3);AK();}
void BB(){w(x+3);AL();}
void BC(){w(x+3);AM();}
void BD(){w(x+3);AN();}
void BE(){w(x+3);AO();}
void BF(){w(x+3);AP();}
void BG(){w(x+2);e();}
void BH(){w(x+2);AB();}
void BI(){w(x+2);AC();}
void BJ(){w(x+2);AD();}
void BK(){w(x+2);AE();}
void BL(){w(x+2);AF();}
void BM(){w(x+2);AG();}
void BN(){w(x+2);AH();}
void BO(){w(x+2);AI();}
void BP(){w(x+2);AJ();}
void BQ(){w(x+2);AK();}
void BR(){w(x+2);AL();}
void BS(){w(x+2);AM();}
void BT(){w(x+2);AN();}
void BU(){w(x+2);AO();}
void BV(){w(x+2);AP();}
void BW(){w(x+2);AQ();}
void BX(){w(x+2);AR();}
void BY(){w(x+2);AS();}
void BZ(){w(x+2);AT();}
void CA(){w(x+2);AU();}
void CB(){w(x+2);AV();}
void CC(){w(x+2);AW();}
void CD(){w(x+2);AX();}
void CE(){w(x+2);AY();}
void CF(){w(x+2);AZ();}
void CG(){w(x+2);BA();}
void CH(){w(x+2);BB();}
void CI(){w(x+2);BC();}
void CJ(){w(x+2);BD();}
void CK(){w(x+2);BE();}
void CL(){w(x+2);BF();}
void CM(){w(x+1);e();}
void CN(){w(x+1);AB();}
void CO(){w(x+1);AC();}
void CP(){w(x+1);AD();}
void CQ(){w(x+1);AE();}
void CR(){w(x+1);AF();}
void CS(){w(x+1);AG();}
void CT(){w(x+1);AH();}
void CU(){w(x+1);AI();}
void CV(){w(x+1);AJ();}
void CW(){w(x+1);AK();}
void CX(){w(x+1);AL();}
void CY(){w(x+1);AM();}
void CZ(){w(x+1);AN();}
void DA(){w(x+1);AO();}
void DB(){w(x+1);AP();}
void DC(){w(x+1);AQ();}
void DD(){w(x+1);AR();}
void DE(){w(x+1);AS();}
void DF(){w(x+1);AT();}
void DG(){w(x+1);AU();}
void DH(){w(x+1);AV();}
void DI(){w(x+1);AW();}
void DJ(){w(x+1);AX();}
void DK(){w(x+1);AY();}
void DL(){w(x+1);AZ();}
void DM(){w(x+1);BA();}
void DN(){w(x+1);BB();}
void DO(){w(x+1);BC();}
void DP(){w(x+1);BD();}
void DQ(){w(x+1);BE();}
void DR(){w(x+1);BF();}
void DS(){w(x+1);BG();}
void DT(){w(x+1);BH();}
void DU(){w(x+1);BI();}
void DV(){w(x+1);BJ();}
void DW(){w(x+1);BK();}
void DX(){w(x+1);BL();}
void DY(){w(x+1);BM();}
void DZ(){w(x+1);BN();}
void EA(){w(x+1);BO();}
void EB(){w(x+1);BP();}
void EC(){w(x+1);BQ();}
void ED(){w(x+1);BR();}
void EE(){w(x+1);BS();}
void EF(){w(x+1);BT();}
void EG(){w(x+1);BU();}
void EH(){w(x+1);BV();}
void EI(){w(x+1);BW();}
void EJ(){w(x+1);BX();}
void EK(){w(x+1);BY();}
void EL(){w(x+1);BZ();}
void EM(){w(x+1);CA();}
void EN(){w(x+1);CB();}
void EO(){w(x+1);CC();}
void EP(){w(x+1);CD();}
void EQ(){w(x+1);CE();}
void ER(){w(x+1);CF();}
void ES(){w(x+1);CG();}
void ET(){w(x+1);CH();}
void EU(){w(x+1);CI();}
void EV(){w(x+1);CJ();}
void EW(){w(x+1);CK();}
void EX(){w(x+1);CL();}
void EY(){w(x);e();}
void EZ(){w(x);AB();}
void FA(){w(x);AC();}
void FB(){w(x);AD();}
void FC(){w(x);AE();}
void FD(){w(x);AF();}
void FE(){w(x);AG();}
void FF(){w(x);AH();}
void FG(){w(x);AI();}
void FH(){w(x);AJ();}
void FI(){w(x);AK();}
void FJ(){w(x);AL();}
void FK(){w(x);AM();}
void FL(){w(x);AN();}
void FM(){w(x);AO();}
void FN(){w(x);AP();}
void FO(){w(x);AQ();}
void FP(){w(x);AR();}
void FQ(){w(x);AS();}
void FR(){w(x);AT();}
void FS(){w(x);AU();}
void FT(){w(x);AV();}
void FU(){w(x);AW();}
void FV(){w(x);AX();}
void FW(){w(x);AY();}
void FX(){w(x);AZ();}
void FY(){w(x);BA();}
void FZ(){w(x);BB();}
void GA(){w(x);BC();}
void GB(){w(x);BD();}
void GC(){w(x);BE();}
void GD(){w(x);BF();}
void GE(){w(x);BG();}
void GF(){w(x);BH();}
void GG(){w(x);BI();}
void GH(){w(x);BJ();}
void GI(){w(x);BK();}
void GJ(){w(x);BL();}
void GK(){w(x);BM();}
void GL(){w(x);BN();}
void GM(){w(x);BO();}
void GN(){w(x);BP();}
void GO(){w(x);BQ();}
void GP(){w(x);BR();}
void GQ(){w(x);BS();}
void GR(){w(x);BT();}
void GS(){w(x);BU();}
void GT(){w(x);BV();}
void GU(){w(x);BW();}
void GV(){w(x);BX();}
void GW(){w(x);BY();}
void GX(){w(x);BZ();}
void GY(){w(x);CA();}
void GZ(){w(x);CB();}
void HA(){w(x);CC();}
void HB(){w(x);CD();}
void HC(){w(x);CE();}
void HD(){w(x);CF();}
void HE(){w(x);CG();}
void HF(){w(x);CH();}
void HG(){w(x);CI();}
void HH(){w(x);CJ();}
void HI(){w(x);CK();}
void HJ(){w(x);CL();}
void HK(){w(x);CM();}
void HL(){w(x);CN();}
void HM(){w(x);CO();}
void HN(){w(x);CP();}
void HO(){w(x);CQ();}
void HP(){w(x);CR();}
void HQ(){w(x);CS();}
void HR(){w(x);CT();}
void HS(){w(x);CU();}
void HT(){w(x);CV();}
void HU(){w(x);CW();}
void HV(){w(x);CX();}
void HW(){w(x);CY();}
void HX(){w(x);CZ();}
void HY(){w(x);DA();}
void HZ(){w(x);DB();}
void IA(){w(x);DC();}
void IB(){w(x);DD();}
void IC(){w(x);DE();}
void ID(){w(x);DF();}
void IE(){w(x);DG();}
void IF(){w(x);DH();}
void IG(){w(x);DI();}
void IH(){w(x);DJ();}
void II(){w(x);DK();}
void IJ(){w(x);DL();}
void IK(){w(x);DM();}
void IL(){w(x);DN();}
void IM(){w(x);DO();}
void IN(){w(x);DP();}
void IO(){w(x);DQ();}
void IP(){w(x);DR();}
void IQ(){w(x);DS();}
void IR(){w(x);DT();}
void IS(){w(x);DU();}
void IT(){w(x);DV();}
void IU(){w(x);DW();}
void IV(){w(x);DX();}
void IW(){w(x);DY();}
void IX(){w(x);DZ();}
void IY(){w(x);EA();}
void IZ(){w(x);EB();}
void JA(){w(x);EC();}
void JB(){w(x);ED();}
void JC(){w(x);EE();}
void JD(){w(x);EF();}
void JE(){w(x);EG();}
void JF(){w(x);EH();}
void JG(){w(x);EI();}
void JH(){w(x);EJ();}
void JI(){w(x);EK();}
void JJ(){w(x);EL();}
void JK(){w(x);EM();}
void JL(){w(x);EN();}
void JM(){w(x);EO();}
void JN(){w(x);EP();}
void JO(){w(x);EQ();}
void JP(){w(x);ER();}
void JQ(){w(x);ES();}
void JR(){w(x);ET();}
void JS(){w(x);EU();}
void JT(){w(x);EV();}
void JU(){w(x);EW();}
void JV(){w(x);EX();}
